# Generated by Django 5.2.5 on 2025-08-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=100)),
            ],
        ),
    ]
